baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'My Craft Project Ddev'
primary: true
siteGroup: 656c477a-2107-46b2-81c8-e796d814769d # My Craft Project Ddev
sortOrder: 1
