fieldLayouts:
  0e254596-cae8-4da6-8629-b58d37c3fb33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 17f52ce5-a321-4572-8562-e2880f59b862
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3add8f81-f602-4025-b9d5-c195449c09dc
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
