columnSuffix: null
contentColumnType: string
fieldGroup: affd83a9-1733-4bd2-b4df-4793174450c4 # Home Page
handle: heroImage
instructions: null
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:ddb77590-4110-4f89-b1fe-29332be5df00' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:7b7a3985-c614-46aa-bf06-e0cf56063c87' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a background Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:ddb77590-4110-4f89-b1fe-29332be5df00' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
